# Generated by Django 4.1.7 on 2023-04-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symtoms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasesymtoms',
            name='name',
        ),
        migrations.AddField(
            model_name='diseasesymtoms',
            name='question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
