# Generated by Django 4.1.7 on 2023-05-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symtoms', '0002_remove_diseasesymtoms_name_diseasesymtoms_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasesymtoms',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diseasesymtoms',
            name='diseases_type',
        ),
        migrations.RemoveField(
            model_name='diseasesymtoms',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='diseasesymtoms',
            name='question',
        ),
        migrations.RemoveField(
            model_name='diseasesymtoms',
            name='updated_at',
        ),
    ]
