# Generated by Django 4.0.6 on 2023-12-06 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('symtoms', '0007_symtoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosticinfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('diagnostic_test', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('prescriptions', models.TextField()),
                ('actual_daignoses', models.CharField(max_length=255)),
                ('predicted_daignoses', models.CharField(max_length=255)),
                ('correct_status', models.CharField(choices=[('Right', 'Right'), ('Wrong', 'Wrong'), ('Partially Right', 'Partially Right')], max_length=20)),
                ('difficult_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('prediction_model', models.CharField(choices=[('Live', 'Live'), ('Beta', 'Beta')], max_length=20)),
                ('feedback', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='diseases',
            name='probability',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='version_list',
            field=models.CharField(choices=[('v1', 'v1'), ('v2', 'v2'), ('v3', 'v3'), ('v4', 'v4'), ('v5', 'v5'), ('v6', 'v6'), ('v7', 'v7'), ('v8', 'v8')], max_length=5),
        ),
    ]
